Uruntakip/Controllers/MachineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Uruntakip.Models;
using Uruntakip.db;
using System.Security.Cryptography;
using System.Diagnostics;

namespace Uruntakip.Controllers
{
    public class MachineController : Controller
    {
        // GET: Machine

        uruntakipdbEntities3 db = new uruntakipdbEntities3();
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }
        [Authorize]
        public ActionResult _makinalar()
        {
            List<cls_makinalar> liste = (from c in db.tblCustomer join m in db.tblmakina on c.firmaid equals m.musteri_id join t in db.tblmakinatipi on m.makinatip_id equals t.tipid select (new cls_makinalar { _firmaadi = c.firmaadi, _makinaid = m.makinaid, _makinaserino = m.serino, _makinatipi = t.makinatipi })).ToList();
            return Json(liste, JsonRequestBehavior.AllowGet);

        }
        [Authorize]
        public ActionResult _makinasahibi(int makinaid)
        {
            tblmakina m = db.tblmakina.FirstOrDefault(x => x.makinaid == makinaid);
            tblCustomer musteri = db.tblCustomer.FirstOrDefault(x => x.firmaid == m.musteri_id);


            return Json(musteri, JsonRequestBehavior.AllowGet);
        }
        [Authorize]
        public ActionResult _makinabul(int makinaid)
        {
            tblmakina t = db.tblmakina.FirstOrDefault(x => x.makinaid == makinaid);

            return Json(t, JsonRequestBehavior.AllowGet);
        }
        [Authorize]
        public ActionResult _makinatipi()
        {

            List<tblmakinatipi> makinatipi = db.tblmakinatipi.ToList();
            return Json(makinatipi, JsonRequestBehavior.AllowGet);
        }
        [Authorize]
        public ActionResult _makinaguncelle(int makinaid, int firmaid, int makinatipi, string makinaserino)
        {
            string sonuc = "";
            try
            {
                tblmakina guncellenen = db.tblmakina.FirstOrDefault(x => x.makinaid == makinaid);
                guncellenen.makinatip_id = makinatipi;
                guncellenen.musteri_id = firmaid;
                guncellenen.serino = makinaserino;
                db.SaveChanges();
                sonuc = "1";
            }
            catch (Exception)
            {

                sonuc = "0";
            }
            return Json(sonuc, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        public ActionResult makinalistesi()
        {
            return View();
        }
        
        
        [Authorize]
        public ActionResult arizalistesi()
        {
            List<cls_arizalistesi> listeler = new List<cls_arizalistesi>();
            List<tblarizalar> arızalar = db.tblarizalar.ToList();
            foreach (tblarizalar item in arızalar)
            {
                var liste = (from f in db.tblCustomer
                             join m in db.tblmakina on f.firmaid equals m.musteri_id
                             join mt in db.tblmakinatipi on m.makinatip_id equals mt.tipid
                             join a in db.tblarizalar on m.makinaid equals a.makina_id
                             join n in db.tblarizaislemleri on a.arizaid equals n.ariza_id
                             join s in db.tblarızasonuctipleri on n.islemtipi equals s.arizasonuc_id
                             where a.arizaid == item.arizaid
                             orderby n.islem_id descending
                             select new { a.arizaid, a.tanım, a.tarih, f.firmaadi, mt.makinatipi, m.serino, s.durum }).Take(1);

                foreach (var itm in liste)
                {
                    if (itm.durum != "Tamamlandı" && itm.durum != "İptal Edildi")
                    {
                        cls_arizalistesi c = new cls_arizalistesi();
                        c._arizano = itm.arizaid;
                        c.tarih2 = Convert.ToDateTime(item.tarih).ToShortDateString();
                        c._arizatanimi = itm.tanım;
                        c._durum = itm.durum;
                        c._firmaadi = itm.firmaadi;
                        c._makinatipi = itm.makinatipi;
                        c._serino = itm.serino;
                        listeler.Add(c);
                    }
                    
                    
                }
                                          
            }
           

            return View(listeler);
        }
       [Authorize]
       public ActionResult parcalistesi()
        {
            return View();
        }
    

    }
}

Uruntakip/Controllers/StokController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using System.Web.WebPages.Html;
using System.Xml;
using Uruntakip.db;
using Uruntakip.Models;

namespace Uruntakip.Controllers
{
    public class StokController : Controller
    {
        // GET: Urun
        uruntakipdbEntities3 db = new uruntakipdbEntities3();
        public ActionResult Index()
        {
            return View();
        }
        public string tarihduzelt_gun_ay_yıl(string m)
        {
            string tarih = Convert.ToDateTime(m).ToShortDateString();  // 2020.08.19 seklınde gelen tarıhı 19.08.2020 formatına cevırdık datetıme yazmak ıcın

            return tarih;
        }
        [Authorize]
        public ActionResult tedarikci()
        {
            List<tblkategori> liste = db.tblkategori.ToList();
           
            return View(liste);
        }
        // -----------------------------------------------------Tedarikci ekleme-------------------------------
        [Authorize]
        [HttpPost]
        public ActionResult tedarikci(FormCollection frm)
        {
            List<tblkategori> liste = db.tblkategori.ToList();
         

            try
            {
                tblCustomer t = new tblCustomer();
                t.adres = frm["adres"].ToString();
                t.firmaadi = frm["firmaadı"].ToUpper().ToString();
                t.ad = frm["adı"].ToString().Trim();
                t.soyad = frm["soyadı"].ToString().Trim();
                t.email = frm["email"].ToString();
                t.telefon = frm["telefon"].ToString();
                t.musteritipi = 0;
                db.tblCustomer.Add(t);
                db.SaveChanges();
                tblefirmaurun_kategorisi k = new tblefirmaurun_kategorisi();
                k.firmaid = t.firmaid;
                k.kategoriid = Convert.ToInt32(frm["kategori"]);
                db.tblefirmaurun_kategorisi.Add(k);

                db.SaveChanges();
                ViewBag.mesaj = 1;
            }
            catch (Exception)
            {

                ViewBag.mesaj = 0;
            }
            
            return View(liste);
        }
        [Authorize]
        //-----------------------------------------------------------tedarikci bilgileri jquery ıle alınıyor
        public ActionResult _tedarickibilgileri(int id)
        {
            List<cls_musteriler> liste = (from c in db.tblCustomer
                                          join k in db.tblefirmaurun_kategorisi on c.firmaid equals k.firmaid
                                          join m in db.tblkategori on k.kategoriid equals m.kategoriID
                                          where c.firmaid == id
                                          select (new cls_musteriler { _musteriid = c.firmaid, _adres = c.adres, _email = c.email, _firmaadi = c.firmaadi, _personelad = c.ad, _personelsoyad = c.soyad, _urunkategori = m.kategoriadi, _telefon = c.telefon, _urunkatid = m.kategoriID })).ToList();
            return Json(liste, JsonRequestBehavior.AllowGet);
        }
        [Authorize]

        //-----------------------------------------------------------butun tedarıkcıler cekılıyor
        public ActionResult _tedarikcilerigetir()
        {
            List<cls_musteriler> liste = (from c in db.tblCustomer
                                          join k in db.tblefirmaurun_kategorisi on c.firmaid equals k.firmaid
                                          join m in db.tblkategori on k.kategoriid equals m.kategoriID
                                          select (new cls_musteriler { _musteriid = c.firmaid, _adres = c.adres, _email = c.email, _firmaadi = c.firmaadi, _personelad = c.ad, _personelsoyad = c.soyad, _urunkategori = m.kategoriadi, _telefon = c.telefon })).ToList();
            return Json(liste, JsonRequestBehavior.AllowGet);
        }[Authorize]

        //--------------------------------------------------------tedarikci bilgileri jquery ıle guncellenıyor
        public ActionResult _tedarikci_bilgilerini_guncelle(int musteriid, string firmaadi, string personelad, string personelsoyad, string email, string telefon, int kategori, string adres)
        {
            int sonuc = 0;
            try
            {
                tblCustomer c = db.tblCustomer.FirstOrDefault(x => x.firmaid == musteriid);
                c.adres = adres;
                c.ad = personelad;
                c.email = email;
                c.firmaadi = firmaadi;
                c.soyad = personelsoyad;
                c.telefon = telefon;
                tblefirmaurun_kategorisi t = db.tblefirmaurun_kategorisi.FirstOrDefault(x => x.firmaid == musteriid);
                t.kategoriid = kategori;
                db.SaveChanges();
                sonuc = 1;

            }
            catch (Exception)
            {

                sonuc = 0;
            }
            return Json(sonuc, JsonRequestBehavior.AllowGet);
        }



        [Authorize]
        public ActionResult tedarikciler()
        {

            return View();
        }
        [Authorize]
        //----------------------------------------------------------- firmanın urun kategorileri bilgileri alınıyor----------------------
        public ActionResult _firmaurunkategorisi(int id)
        {
            List<cls_musteriler> liste = (from k in db.tblefirmaurun_kategorisi
                                          join i in db.tblkategori on k.kategoriid equals i.kategoriID
                                          join m in db.tblCustomer on k.firmaid equals m.firmaid
                                          where m.firmaid == id
                                          select (new cls_musteriler { _urunkatid = (int)k.kategoriid, _urunkategori = i.kategoriadi })).ToList();
            return Json(liste, JsonRequestBehavior.AllowGet);

        }


        [Authorize]
        public ActionResult stokkarti()
        {
           List< tblkategori> urunkategorisi = db.tblkategori.ToList();
            ViewBag.tedarikci = db.tblCustomer.Where(x => x.musteritipi == 0).ToList();
            
            return View(urunkategorisi);
        }
        [Authorize]
        //------------------------------------------------stok kartı olusturuluyor------------------------
        [HttpPost]
        public ActionResult stokkarti(FormCollection frm)
        {
            List<tblkategori> urunkategorisi = db.tblkategori.ToList();
            ViewBag.tedarikci = db.tblCustomer.Where(x => x.musteritipi == 0).ToList();

            string urunadi = frm["ad"].ToUpper().ToString().Trim();
            tblurunler urun = db.tblurunler.FirstOrDefault(x => x.urunadi ==urunadi );
            if(urun==null)
            {
                try
                {
                    tblurunler yeniurun = new tblurunler();
                    yeniurun.tedarikci_id =Convert.ToInt32( frm["tedarikci"].ToString().Trim());
                    yeniurun.urunadi = frm["ad"].ToUpper().Trim();
                    yeniurun.urun_fiyati = Convert.ToDecimal(frm["fiyat"].ToString().Trim());
                    yeniurun.urunkategori = Convert.ToInt32(frm["kategori"]);
                    db.tblurunler.Add(yeniurun);
                   
                    db.SaveChanges();
                    tblurundetayları t = new tblurundetayları();
                    
                    ViewBag.mesaj = 1;
                }
                catch (Exception)
                {

                    ViewBag.mesaj = 2;
                }
            }
            else
            {
                ViewBag.mesaj = 0;
            }
            return View(urunkategorisi);
        }
        
        [Authorize]
        public ActionResult urunekle()
        {
          var  liste = db.tblurunler.ToList().Take(10);
            List<tblurunler> t = new List<tblurunler>();
            foreach (var item in liste)
            {
                tblurunler n = new tblurunler();
                n =(tblurunler) item;
                t.Add(n); 
            }
           
            ViewBag.urunler = t;

            return View();

        }
        [Authorize]
        //---------------------------------------------yenı urun eklenıyor--------------------
        [HttpPost]
        public ActionResult urunekle(FormCollection frm)
        {
            int urunid = Convert.ToInt32(frm["urun"].ToString());
            tblurunler p = db.tblurunler.FirstOrDefault(x => x.uruid == urunid);

            var liste = db.tblurunler.ToList().Take(10);
            List<tblurunler> t = new List<tblurunler>();
            foreach (var item in liste)
            {
                tblurunler n = new tblurunler();
                n = (tblurunler)item;
                t.Add(n);
            }
            ViewBag.urunler = t;

            if(string.IsNullOrEmpty(frm["serino"].ToString())) //urunde serı numarası yoksa ekleme ıslemı ona yapılacak
            {
                try
                {
                    tblurundetayları yeniurun = db.tblurundetayları.FirstOrDefault(x=>x.urun_id==urunid);
                    if(yeniurun==null)
                    {
                        yeniurun = new tblurundetayları();
                        yeniurun.urun_id = Convert.ToInt32(frm["urun"].ToString());
                        yeniurun.urunserino = frm["serino"].ToString();
                        yeniurun.adet = Convert.ToInt32(frm["adet"].ToString());
                        db.tblurundetayları.Add(yeniurun);
                        db.SaveChanges();

                        tblurun_islem_Gecmisi u = new tblurun_islem_Gecmisi();
                        u.urun_detay_id = yeniurun.detay_id;
                        u.islem_tarihi = DateTime.Now.Date;
                        u.uruneskimusteri = p.tedarikci_id;
                        u.urunyenimusteri = 1007;

Uruntakip/Views/Shared/main.cshtml
@{
    Layout = null;
}


<!DOCTYPE html>
<html lang="en">
<head>
    <title>Funder &mdash; Colorlib Website Template</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="~/vendor/sweetalert.min.js"></script>

    <link rel="stylesheet" href="~/Content/anasayfadosyaları/fonts/icomoon/style.css" />
    <link href="~/Content/anasayfadosyaları/css/bootstrap/bootstrapp.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Content/anasayfadosyaları/css/style.css">
    <script src="~/Scripts/moment.js"></script>
    @* ----------------benım script dosyalarım------------------------*@

    <script src="~/myscripts/customercodes.js"></script>
    <script src="~/myscripts/makinaislemleri.js"></script>
    <script src="~/myscripts/arizaislemleri.js"></script>
    <script src="~/myscripts/urunislemleri.js"></script>
  
    @*----------------------------------------------------------------*@
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

    <link href="~/Scripts/DataTables/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="~/Scripts/DataTables/css/responsive.bootstrap.min.css" rel="stylesheet" />

    <script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>

    <script src="~/Scripts/DataTables/dataTables.bootstrap4.js"></script>





</head>
<body>
    <div class="site-navbar-wrap js-site-navbar">
        <div class="site-navbar">
            <nav class="site-navigation text-center" role="navigation" style="background-color:rgba(120, 221, 177, 0.91)" )>


                <ul class="site-menu js-clone-nav d-none d-lg-block">

                    <li class="has-children">
                        <a href="#"><b>Müşteri İşlemleri</b></a>
                        <ul class="dropdown arrow-top">
                            <li><a href="@Url.Action("musteriekle","Customer")">Müşteri Ekle</a></li>
                            <li><a href="@Url.Action("musterilistesi","Customer")">Müşteri Listesi</a></li>
                        
                        </ul>
                    </li>


                    <li class="has-children">
                        <a href="#"><b>Makina İşlemleri</b></a>
                        <ul class="dropdown">

                            <li><a href="@Url.Action("makinalistesi","Machine")">Makina Listesi</a></li>
                           

                        </ul>
                    </li>

                    <li class="has-children">
                        <a href="#"><b>Servis İşlemleri</b></a>
                        <ul class="dropdown">

                            <li><a href="@Url.Action("arizalistesi","Machine")">Arıza Listesi</a></li>
                            

                        </ul>
                    </li>
                    <li class="has-children">
                        <a href="#"><b>Depo işlemleri</b></a>
                        <ul class="dropdown">

                            <li><a href="@Url.Action("tedarikci","Stok")">Tedarikçi Ekle</a></li>
                            <li><a href="@Url.Action("tedarikciler","Stok")">Tedarikçi Listesi</a></li>
                            <li><a href="@Url.Action("stokkarti","Stok")">Stok Kartı Oluştur</a></li>
                            <li><a href="@Url.Action("urunekle","Stok")">Ürün Ekle</a></li>
                            <li><a href="@Url.Action("urunlistesi","Stok")">Ürün listesi</a></li>
                      
                        </ul>
                    </li>


                </ul>

            </nav>
        </div>
    </div>


    <div>
        @RenderBody()
    </div>


    <div class="modal fade" id="ShowModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header" style="text-align:center">
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                    <h3>Kayıt Formu</h3>

                </div>
                <div class="modal-body">
                    <form id="Registration">

                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
                                <input class="form-control" type="email" name="Email" id="userposta" placeholder="Email" />
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                                <input class="form-control" type="password" name="Password" id="usersifre" placeholder="Password" />
                            </div>
                        </div>
                    </form>
                    <div class="form-group">
                        <button class="btn btn-info form-control" type="button" onclick="hesabikayet()"> KAYDET</button>
                    </div>
                </div>
            </div>
        </div>
    </div>





</body>
</html>