Uruntakip/Controllers/ArizaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using Uruntakip.db;
using Uruntakip.Models;

namespace Uruntakip.Controllers
{
    public class ArizaController : Controller
    {
        // GET: Ariza
        uruntakipdbEntities3 db = new uruntakipdbEntities3();
        [Authorize]
        public ActionResult Index()
            
        { 
            
            return View();
        }
        [Authorize]
        //-----------------------------------------------------ARIZALAR ICIN YAPILAN ISLEMLER GIRILIYOR---------
        public ActionResult _arizaislemleri(int arizano,string islem,DateTime tarih,int islemtipi)
        {
            string sonuc = "0";
            try
            {
                tblarizaislemleri t = new tblarizaislemleri();
                t.aciklama = islem;
                t.ariza_id = arizano;
                t.islemtarihi = tarih;
                t.islemtipi = islemtipi;
                db.tblarizaislemleri.Add(t);
                db.SaveChanges();
                sonuc = "1";

            }
            catch (Exception)
            {

                sonuc = "0";
            }
            return Json(sonuc, JsonRequestBehavior.AllowGet);

            

        }
        [Authorize]
        //--------------------------------------------------------MAKINAYA AIT BUTUN ARIZALAR CEKILIYOR------------------
        public ActionResult _arizagecmisi(int makinaid)
        {
            List<cls_arizalistesi> gidicekliste = new List<cls_arizalistesi>();
            List<tblarizalar> arizalistesi = db.tblarizalar.Where(x => x.makina_id == makinaid).ToList();
            foreach (var item in arizalistesi)
            {
                var liste = (from a in db.tblarizalar
                             join k in db.tblarizakategorileri on a.kategori_id equals k.ariza_kategori_ID
                             join i in db.tblarizaislemleri on a.arizaid equals i.ariza_id
                             join s in db.tblarızasonuctipleri on i.islemtipi equals s.arizasonuc_id
                             where a.makina_id == makinaid&&a.arizaid==item.arizaid
                             orderby s.arizasonuc_id descending
                             select (new cls_arizalistesi { _arizano = a.arizaid, tarih2 = a.tarih.ToString(), _arizatanimi = a.tanım, _durum = s.durum, _kategoriadi = k.kategoriadi })).ToList().Take(1);
                
                
                foreach (var itm in liste)
                {
                    cls_arizalistesi c = new cls_arizalistesi();
                    c._arizano = itm._arizano;
                    c.tarih2 = itm.tarih2;
                    c._arizatanimi = itm._arizatanimi;
                    c._durum = itm._durum;
                    c._kategoriadi = itm._kategoriadi;

                    gidicekliste.Add(c);
                }
                
                

            }

            foreach (var item in gidicekliste)
            {
                item.tarih2 = tarihduzelt_gun_ay_yıl(item.tarih2);
            }

            return Json(gidicekliste, JsonRequestBehavior.AllowGet);
        }
        [Authorize]
        //---------------------------------------------------------ARIZA BILGILERI GUNCELLENIYOR-----------------------

        public ActionResult _arizaguncelle(int arizano, int kategori, string tanim, DateTime tarih)
        {
            string sonuc = "0";
            try
            {
                tblarizalar t = db.tblarizalar.FirstOrDefault(x => x.arizaid == arizano);
                t.kategori_id = kategori;
                t.tanım = tanim;
                t.tarih = tarih;
                db.SaveChanges();
                sonuc = "1";

            }
            catch (Exception)
            {

                sonuc = "0";
            }

            return Json(sonuc, JsonRequestBehavior.AllowGet);
        }
        [Authorize]

        // ---------------------------------------------------------TARIH FORMATI DEGISTIRILIYOR----------------
        public string tarihduzelt_yıl_ay_gun(string tt)
        {
            string v = Convert.ToDateTime(tt).ToShortDateString();  // 19.09.2020 seklınde gelen tarıhı 2020-09-19 formatına cevırdık datetımepickere yazmak ıcın
            var t = v.Split('/');
          string tarih = t[2] + '-' + t[1] + '-' + t[0];
            return tarih;
        }
        public string tarihduzelt_gun_ay_yıl(string m)
        {
            string tarih = Convert.ToDateTime(m).ToShortDateString();  // 2020.08.19 seklınde gelen tarıhı 19.08.2020 formatına cevırdık datetıme yazmak ıcın
           
            return tarih;
        }
        //-------------------------------------------------------------ARIZAYA AIT BILGILER CEKILIYOR--------------------
        [Authorize]
        public ActionResult _arizabilgileri(int arizano)
        {
            tblarizalar aranan = db.tblarizalar.FirstOrDefault(x => x.arizaid == arizano);
            cls_arizalistesi c = new cls_arizalistesi();
            c._makinaid = (int)aranan.makina_id;
            c._kategoriid = (int)aranan.kategori_id;
            c._arizatanimi = aranan.tanım;
            c.tarih2 = tarihduzelt_yıl_ay_gun(aranan.tarih.ToString());  // 19.09.2020 seklınde gelen tarıhı 2020-09-19 formatına cevırdık datetıme pickera yazmak ıcın
            
            return Json(c, JsonRequestBehavior.AllowGet);

        }
        // -----------------------------------------------------------MAKINA TIPINE GORE ARIZA KATEGORILERI CEKILIYOR----------
        [Authorize]
        public ActionResult _arizakategorileri(int makinaid)
        {
            tblmakina mc = db.tblmakina.FirstOrDefault(x => x.makinaid == makinaid);
            List<tblarizakategorileri> liste = db.tblarizakategorileri.Where(x => x.makinatipi == mc.makinatip_id).ToList();
            return Json(liste, JsonRequestBehavior.AllowGet);
        }
        [Authorize]

        //----------------------------------------------------------ARIZA KAYDI OLUSTURULUYOR--------------
        public ActionResult yeniarizakaydi(int makinaid, int kategori, string tanım, DateTime tarih)
        {
            int sonuc = 0;
            try
            {
                tblarizalar arz = new tblarizalar();
                arz.makina_id = makinaid;
                arz.kategori_id = kategori;
                arz.tanım = tanım;
                arz.tarih = tarih.Date;
                arz.durum = 1;
                db.tblarizalar.Add(arz);
                db.SaveChanges();
                //işlem tablosunada verileri ekledik.
                tblarizaislemleri islem = new tblarizaislemleri();
                islem.ariza_id = arz.arizaid;
                islem.aciklama = arz.tanım;
                islem.islemtarihi = arz.tarih;
                islem.islemtipi = arz.durum;
                db.tblarizaislemleri.Add(islem);
                db.SaveChanges();
                sonuc = 1;
            }
            catch (Exception)
            {

                sonuc = 0;
            }

            return Json(sonuc, JsonRequestBehavior.AllowGet);
        }
  



        //----------------------------------------------ARIZA ICIN YAPILAN ISLEM DETAYLARI CEKILIYOR---------

        [Authorize]
        public ActionResult arizadetayı(int id)
        {
            List<cls_arizalistesi> liste = (from i in db.tblarizaislemleri
                       join a in db.tblarizalar on i.ariza_id equals a.arizaid
                       join k in db.tblarizakategorileri on a.kategori_id equals k.ariza_kategori_ID
                       join s in db.tblarızasonuctipleri on i.islemtipi equals s.arizasonuc_id
                       join m in db.tblmakina on a.makina_id equals m.makinaid
                       where i.ariza_id == id
                       orderby i.islem_id descending
                       select( new cls_arizalistesi{_islemid= i.islem_id,tarih2= i.islemtarihi.ToString(),_arizatanimi= i.aciklama,_durum= s.durum })).ToList();



            


            return View(liste);
        }
        [Authorize]
        //-----------------------------------------------ACIK OLAN ARIZALAR CEKILIYOR-------------------
        public ActionResult _arizalistesinicek()
        {
            List<cls_arizalistesi> listeler = new List<cls_arizalistesi>();
            List<tblarizalar> arızalar = db.tblarizalar.ToList();
            foreach (tblarizalar item in arızalar)
            {
                var liste = (from f in db.tblCustomer
                             join m in db.tblmakina on f.firmaid equals m.musteri_id
                             join mt in db.tblmakinatipi on m.makinatip_id equals mt.tipid
                             join a in db.tblarizalar on m.makinaid equals a.makina_id
                             join n in db.tblarizaislemleri on a.arizaid equals n.ariza_id
                             join s in db.tblarızasonuctipleri on n.islemtipi equals s.arizasonuc_id
                             where a.arizaid == item.arizaid 
                             orderby n.islem_id descending
                             select new { a.arizaid, a.tanım, a.tarih, f.firmaadi, mt.makinatipi, m.serino, s.durum }).Take(1);

                foreach (var itm in liste)
                {
                    if (itm.durum != "Tamamlandı" && itm.durum != "İptal Edildi")
                    {
                        cls_arizalistesi c = new cls_arizalistesi();
                        c._arizano = itm.arizaid;
                        c.tarih2 = Convert.ToDateTime(item.tarih).ToShortDateString();
                        c._arizatanimi = itm.tanım;
                        c._durum = itm.durum;
                        c._firmaadi = itm.firmaadi;
                        c._makinatipi = itm.makinatipi;
                        c._serino = itm.serino;
                        listeler.Add(c);
                    }
                   
                       

Uruntakip/Controllers/MachineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Uruntakip.Models;
using Uruntakip.db;
using System.Security.Cryptography;
using System.Diagnostics;

namespace Uruntakip.Controllers
{
    public class MachineController : Controller
    {
        // GET: Machine

        uruntakipdbEntities3 db = new uruntakipdbEntities3();
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }
        [Authorize]
        public ActionResult _makinalar()
        {
            List<cls_makinalar> liste = (from c in db.tblCustomer join m in db.tblmakina on c.firmaid equals m.musteri_id join t in db.tblmakinatipi on m.makinatip_id equals t.tipid select (new cls_makinalar { _firmaadi = c.firmaadi, _makinaid = m.makinaid, _makinaserino = m.serino, _makinatipi = t.makinatipi })).ToList();
            return Json(liste, JsonRequestBehavior.AllowGet);

        }
        [Authorize]
        public ActionResult _makinasahibi(int makinaid)
        {
            tblmakina m = db.tblmakina.FirstOrDefault(x => x.makinaid == makinaid);
            tblCustomer musteri = db.tblCustomer.FirstOrDefault(x => x.firmaid == m.musteri_id);


            return Json(musteri, JsonRequestBehavior.AllowGet);
        }
        [Authorize]
        public ActionResult _makinabul(int makinaid)
        {
            tblmakina t = db.tblmakina.FirstOrDefault(x => x.makinaid == makinaid);

            return Json(t, JsonRequestBehavior.AllowGet);
        }
        [Authorize]
        public ActionResult _makinatipi()
        {

            List<tblmakinatipi> makinatipi = db.tblmakinatipi.ToList();
            return Json(makinatipi, JsonRequestBehavior.AllowGet);
        }
        [Authorize]
        public ActionResult _makinaguncelle(int makinaid, int firmaid, int makinatipi, string makinaserino)
        {
            string sonuc = "";
            try
            {
                tblmakina guncellenen = db.tblmakina.FirstOrDefault(x => x.makinaid == makinaid);
                guncellenen.makinatip_id = makinatipi;
                guncellenen.musteri_id = firmaid;
                guncellenen.serino = makinaserino;
                db.SaveChanges();
                sonuc = "1";
            }
            catch (Exception)
            {

                sonuc = "0";
            }
            return Json(sonuc, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        public ActionResult makinalistesi()
        {
            return View();
        }
        
        
        [Authorize]
        public ActionResult arizalistesi()
        {
            List<cls_arizalistesi> listeler = new List<cls_arizalistesi>();
            List<tblarizalar> arızalar = db.tblarizalar.ToList();
            foreach (tblarizalar item in arızalar)
            {
                var liste = (from f in db.tblCustomer
                             join m in db.tblmakina on f.firmaid equals m.musteri_id
                             join mt in db.tblmakinatipi on m.makinatip_id equals mt.tipid
                             join a in db.tblarizalar on m.makinaid equals a.makina_id
                             join n in db.tblarizaislemleri on a.arizaid equals n.ariza_id
                             join s in db.tblarızasonuctipleri on n.islemtipi equals s.arizasonuc_id
                             where a.arizaid == item.arizaid
                             orderby n.islem_id descending
                             select new { a.arizaid, a.tanım, a.tarih, f.firmaadi, mt.makinatipi, m.serino, s.durum }).Take(1);

                foreach (var itm in liste)
                {
                    if (itm.durum != "Tamamlandı" && itm.durum != "İptal Edildi")
                    {
                        cls_arizalistesi c = new cls_arizalistesi();
                        c._arizano = itm.arizaid;
                        c.tarih2 = Convert.ToDateTime(item.tarih).ToShortDateString();
                        c._arizatanimi = itm.tanım;
                        c._durum = itm.durum;
                        c._firmaadi = itm.firmaadi;
                        c._makinatipi = itm.makinatipi;
                        c._serino = itm.serino;
                        listeler.Add(c);
                    }
                    
                    
                }
                                          
            }
           

            return View(listeler);
        }
       [Authorize]
       public ActionResult parcalistesi()
        {
            return View();
        }
    

    }
}

Uruntakip/Views/Machine/arizalistesi.cshtml
@model List<Uruntakip.Models.cls_arizalistesi>
@{
    ViewBag.Title = "arizalistesi";
    Layout = "~/Views/Shared/main.cshtml";
}

    <div style="margin-top:25px">
        <table id="tblarizalistesi" class="table table-hover table-bordered" *>

            <thead>
                <tr>
                    <th scope="col" style="color:#fc6c05;font-size:16px">Ariza No</th>
                    <th scope="col" style="color:#fc6c05;font-size:16px">Tarih</th>
                    <th scope="col" style="color:#fc6c05;font-size:16px">Firma Adı</th>
                    <th scope="col" style="color:#fc6c05;font-size:16px">Makina Tipi</th>
                    <th scope="col" style="color:#fc6c05;font-size:16px" class="no-sort">Makina Serino</th>
                    <th scope="col" style="color:#fc6c05;font-size:16px" class="no-sort">Arıza Tanımı</th>
                    <th scope="col" style="color:#fc6c05;font-size:16px" class="no-sort">Arıza Durumu</th>
                    <th scope="col" style="color:#fc6c05;font-size:16px" class="no-sort">İşlemler</th>


                </tr>
            </thead>
            <tbody >
                 @foreach (var item in Model)
                 {
                <tr>
                    <td><b>@item._arizano</b></td>
                    <td><b>@item.tarih2</b></td>
                    <td><b>@item._firmaadi</b></td>
                    <td><b>@item._makinatipi</b></td>
                    <td><b>@item._serino</b></td>
                    <td><b>@item._arizatanimi</b></td>
                    @if (item._durum == "İşleme Alındı")
                    {
                        <td><b style="color:green">@item._durum</b></td>
                    }
                    else if (item._durum == "Kontrol Ediliyor")
                    {
                        <td><b style="color:red">@item._durum</b></td>
                    }
                    else if(item._durum== "Malzeme Gönderildi")
                    {
                        <td><b style="color:blue">@item._durum</b></td>
                    }

                <td><button id="ekle" value="@item._arizano" class="btn btn-success">Ekle</button> <a href="@Url.Action("arizadetayı","Ariza",new {id=item._arizano })"><input type="button" value="Detay" id="detay" class="btn btn-warning" /></a> <a href="#"><input type="button" value="Görev" id="sevk" class="btn btn-info" /></a> </td>
                </tr>
                 }
            </tbody>
        </table>
    </div>
@* -----------------------------------------Arıza ıcın yapılan ıslemlerı guncelledigimiz form-----------------------*@

<div class="modal fade" id="frmislem">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header" style="text-align:center">
                <a href="#" class="close" data-dismiss="modal">&times;</a>
               
                <div>

                    <span class="" style="color:#fc6c05;font-size:16px"><b>Ariza No :  </b></span>  <span style="font-size:18px;"><b id="frmislem_arizano"></b></span>

                </div>

            </div>
            <div class="modal-body">
                <form id="Registration">
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon" style="width:128px;color:#fc6c05"><b>İşlem Tipi</b></span>
                            <fieldset>
                                <select id="frmislem_islemtipi" class="form-control" style="font-weight:bold">
                                </select>
                            </fieldset>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon" style="width:128px;color:#fc6c05"><b>Yapılan İşlem</b></span>

                            <b><input type="text" id="frmislem_tanim" autocomplete="off" class="form-control" /></b>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon" style="width:128px;color:#fc6c05"><b>İşlem Tarihi</b></span>
                            <b><input type="date" id="frmislem_tarih" class="form-control" /></b>

                        </div>
                    </div>

                </form>
                <div class="form-group">
                    <button class="btn btn-success form-control" type="submit" onclick="islemgirisi()">Yeni işlem Ekle</button>
                </div>
            </div>
        </div>
    </div>
</div>




<script>
    $("#tblarizalistesi").dataTable(
        {
            columnDefs: [
                { targets: 'no-sort', orderable: false }
            ],
            "columns": [
                null,
                null,
                null,
                null,
                null,
                { "width": "25%" },
                null,
                { "width": "16%" }
            ]
            
        }
    );

    islemformunuac();
</script>

Uruntakip/Views/Machine/makinalistesi.cshtml
@{
    ViewBag.Title = "makinalistesi";
    Layout = "~/Views/Shared/main.cshtml";
}

<div style="margin-top:25px">
    <table id="tblmakinalar" class="table table-hover table-bordered" *>

        <thead>
            <tr>
                <th scope="col" style="color:#fc6c05;font-size:16px">Firma Adı</th>
                <th scope="col" style="color:#fc6c05;font-size:16px">Makina Tipi</th>
                <th scope="col" style="color:#fc6c05;font-size:16px" class="no-sort">Makina Serino</th>
                <th scope="col" style="color:#fc6c05;font-size:16px" class="no-sort">Detaylar</th>

            </tr>
        </thead>
        <tbody id="tbody">
            
        </tbody>
    </table>
</div>
<div id="veri" style="margin-left:600px">
    <img src="~/images/yukleniyor.gif"/>

</div>


<br />
<div style="height:60px">
    
</div>
@*-----------------------------------makina bilgilerini guncelleme formu-------------------------------------------*@
<div class="modal fade" id="frmguncelle">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header" style="text-align:center">
           
                <h3 id="frmguncelle_ad" hidden="hidden"></h3>
                <h3 id="frmguncelle_makinaid" hidden="hidden"></h3>
                <div class="form-group">
                    <div class="input-group">
                        <b><input type="text" id="arama" autocomplete="off" class="form-control" /></b>
                        <span class="input-group-addon" style="width:128px;color:#fc6c05" onclick="musteribul()"><b>Firma Arama</b></span>
                    </div>
                </div>
            </div>
           
            <div class="modal-body">
                <form id="Registration">

                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon" style="width:128px;color:#fc6c05"><b>Firma Adı</b></span>
                            <fieldset>
                                <select id="frmguncelle_firmalar" class="form-control" style="font-weight:bold">
                                </select>
                            </fieldset>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon" style="width:128px;color:#fc6c05"><b>Makina Tipi</b></span>

                            <fieldset>
                                <select id="frmguncelle_makinatipi" class="form-control" style="font-weight:bold">
                                </select>
                            </fieldset>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon" style="width:128px;color:#fc6c05"><b>Seri No</b></span>
                            <b><input type="text" id="frmguncelle_serino" class="form-control" /></b>

                        </div>
                    </div>

                </form>
                <div class="form-group">
                    <button class="btn btn-success form-control" type="submit" onclick="makinaguncelle()">Güncelle</button>
                </div>
            </div>
        </div>
    </div>
</div>
@**-----------------------------------------------makina arıza kayıt formu -------------------------------*@


<div class="modal fade" id="frmariza">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header" style="text-align:center">
                <a href="#" class="close" data-dismiss="modal">&times;</a>
                <h3 id="frmariza_serino"></h3>
                <h3 id="frmariza_makinaid" hidden="hidden"></h3>

            </div>
            <div class="modal-body">
                <form id="Registration">

                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon" style="width:128px;color:#fc6c05"><b>Kategorileri</b></span>
                            <fieldset>
                                <select id="frmariza_kategoriler" class="form-control" style="font-weight:bold">
                                </select>
                            </fieldset>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon" style="width:128px;color:#fc6c05"><b>Arıza Tanımı</b></span>

                            <b><input type="text" id="frmariza_tanim" autocomplete="off" class="form-control" /></b>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon" style="width:128px;color:#fc6c05"><b>Arıza Tarihi</b></span>
                            <b><input type="date" id="frmariza_tarih"  class="form-control" /></b>

                        </div>
                    </div>

                </form>
                <div class="form-group">
                    <button class="btn btn-success form-control" type="submit" onclick="arızakaydiac()">Arıza Kayıt</button>
                </div>
            </div>
        </div>
    </div>
</div>
@* -----------------------arıza guncellemrde-----------------------------------*@



<script>
    $("#tblmakinalar").DataTable({
        "columns": [
            null,
            null,
            null,
            { "width": "25%" }
        ],
        columnDefs: [
            { targets: 'no-sort', orderable: false }
        ]
    })

    tummakinalar();
    
    arizaformunuac();
    
    
</script>

Uruntakip/Views/Machine/parcalistesi.cshtml
@{
    ViewBag.Title = "parcalistesi";
    Layout = "~/Views/Shared/main.cshtml";
}
<div class="modal-dialog">
       <form id="Registration">
          <div class="form-group">
              <div class="input-group">
                  <b> <input class="form-control" type="text" id="search_id" placeholder="Makina Seri No" /></b>
                  <span class="input-group-addon" style="width:128px;color:#fc6c05" onclick="test()"><b>Search</b></span>

              </div>
          </div>          
        </form>
</div>

<table id="tblparcalistesi" class="table table-hover table-bordered">

    <thead>
        <tr>
            <th scope="col" style="color:#fc6c05;font-size:16px" class="ters">İşlem No</th>
            <th scope="col" style="color:#fc6c05;font-size:16px" class="no-sort">İşlem Tarihi</th>
            <th scope="col" style="color:#fc6c05;font-size:16px" class="no-sort">Stok Kodu</th>
            <th scope="col" style="color:#fc6c05;font-size:16px" class="no-sort">Stok Adı</th>
            <th scope="col" style="color:#fc6c05;font-size:16px" class="no-sort">Adet</th>
            <th scope="col" style="color:#fc6c05;font-size:16px" class="no-sort">İşlem Tipi</th>

        </tr>
    </thead>
    <tbody>
       

    </tbody>
</table>

<script>
    $("#tblparcalistesi").dataTable({

        "columnDefs": [
            {
                "targets": "no-sort",
                "orderable": false,

            },

        ],
        

    });

    function test() {
        alert("basıldı");
    }

</script>